server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://chatting.cx3635ohpt8d.ap-northeast-2.rds.amazonaws.com/mangoPlateDev?autoReconnect=true # 변경해주세요
    username: root
    password: chat1234 # 변경해주세요

    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전